export const SITE_TITLE = 'Helio | Open-source governance for MCP agents'
export const SITE_DESCRIPTION = 'Helio is an open-source MCP governance proxy for policies, spend limits, approvals, evidence checks, and audit trails. No agent or server code changes.'
export const SITE_URL = 'https://www.helio.so'
export const SITE_IMAGE = '/helio-opengraph.png'
export const SITE_EMAIL = 'hello@helio.so'
export const SITE_BLOG = 'https://www.helio.so/blog/'
export const SITE_SOCIAL_TWITTER = 'https://x.com/get_helio'
export const SITE_SOCIAL_LINKEDIN = 'https://www.linkedin.com/company/get-helio/'
export const SITE_GITHUB = 'https://github.com/gethelio/helio'
export { DESIGN_PARTNER_BOOKING_URL } from './lib/design-partner/constants.js'
