import type { TheaterMode, TheaterScene } from './types'

export const THEATER_ORDER: TheaterMode[] = [
  'policy',
  'budgets',
  'evidence',
  'approvals',
  'drift',
  'audit',
  'repair',
]

export const AUTOPLAY_MS = 4200
export const AUTOPLAY_RESUME_MS = 14000

export const THEATER_SCENES: Record<TheaterMode, TheaterScene> = {
  policy: {
    id: 'policy',
    label: '01 Policy',
    stamp: 'deny',
    stampTone: 'deny',
    client: 'Claude',
    upstream: 'internal',
    tool: 'process_refund',
    args: [
      ['order ', { strong: '9182' }, ' · amount ', { strong: '$2,400' }],
      ['matched rule: amount > 1000'],
    ],
    policy: 'policies:\n  rules:\n    - match:\n        tool: process_refund\n        input:\n          "$.amount": { gt: 1000 }\n      action: deny',
    evidence: 'requires  [orders.lookup]\ndepends   process_refund ← lookup\ngrounding idle',
    drift: 'baseline  frozen\non_tool_drift  block\ndiff  none',
    approval: 'idle',
    approvalTone: 'hold',
    highlight: ['policy'],
    audit: [
      '12:04:01  sess_9x2k  process_refund           DENY     policy.amount_gt_1000',
      '12:04:01  sess_9x2k  would_forward            false    dry_run: off',
      '12:03:44  sess_9x2k  stripe.list_customers    ALLOW    default_allow',
    ],
  },
  budgets: {
    id: 'budgets',
    label: '02 Budgets',
    stamp: 'require_approval',
    stampTone: 'hold',
    client: 'Claude',
    upstream: 'stripe',
    tool: 'stripe.create_payment',
    args: [
      ['amount ', { strong: '$2,400' }, ' USD'],
      ['would breach agent-payments · $47.12 / $50.00'],
    ],
    policy: 'budgets:\n  - name: agent-payments\n    limit: 50\n    currency: USD\n    on_exceed: require_approval',
    evidence: 'requires  —\ndepends   none\ngrounding n/a',
    drift: 'baseline  frozen\non_tool_drift  block\ndiff  none',
    approval: 'break-glass',
    approvalTone: 'hold',
    highlight: ['budgets', 'approvals', 'policy'],
    audit: [
      '12:04:08  sess_9x2k  stripe.create_payment    HELD     budget.agent-payments',
      '12:04:08  sess_9x2k  ledger                   durable  47.12 / 50.00',
      '12:04:08  sess_9x2k  break_glass              slack    #finance',
    ],
  },
  evidence: {
    id: 'evidence',
    label: '03 Evidence',
    stamp: 'deny',
    stampTone: 'deny',
    client: 'Cursor',
    upstream: 'shop',
    tool: 'process_refund',
    args: [['order ', { strong: '9182' }], ['client asked to skip the lookup']],
    policy: 'policies:\n  rules:\n    - match:\n        tool: process_refund\n      action: deny\n      evidence:\n        requires: [orders.lookup]',
    evidence: 'requires  [orders.lookup]\ndepends   process_refund ← lookup\ngrounding missing',
    drift: 'baseline  frozen\non_tool_drift  block\ndiff  none',
    approval: 'idle',
    approvalTone: 'hold',
    highlight: ['evidence', 'policy'],
    audit: [
      '12:04:11  sess_9x2k  process_refund           DENY     evidence_missing',
      '12:04:11  sess_9x2k  missing                  key      orders.lookup',
      '12:04:11  sess_9x2k  self_repair              suggest  call orders.lookup then retry',
    ],
  },
  approvals: {
    id: 'approvals',
    label: '04 Approvals',
    stamp: 'pending',
    stampTone: 'hold',
    client: 'ChatGPT',
    upstream: 'stripe',
    tool: 'stripe.create_payment',
    args: [
      ['amount ', { strong: '$2,400' }, ' USD'],
      ['held for a human in Slack #finance'],
    ],
    policy: 'policies:\n  rules:\n    - match:\n        tool: stripe.create_payment\n      action: require_approval\n      approval:\n        channel: slack',
    evidence: 'requires  —\ndepends   none\ngrounding n/a',
    drift: 'baseline  frozen\non_tool_drift  block\ndiff  none',
    approval: 'waiting',
    approvalTone: 'hold',
    highlight: ['approvals', 'policy'],
    audit: [
      '12:04:14  sess_9x2k  stripe.create_payment    HOLD     require_approval',
      '12:04:14  sess_9x2k  notify                   slack    #finance',
      '12:04:14  sess_9x2k  webhook                  posted   dashboard.queue',
    ],
  },
  drift: {
    id: 'drift',
    label: '05 Drift',
    stamp: 'blocked',
    stampTone: 'deny',
    client: 'LangChain',
    upstream: 'stripe',
    tool: 'stripe.create_payment',
    args: [
      ['tools/list rewritten after review'],
      ['inputSchema + description drifted'],
    ],
    policy: 'policies:\n  on_tool_drift: block\n  tool_revalidation:\n    enabled: true\n    interval: 5m',
    evidence: 'requires  —\ndepends   none\ngrounding n/a',
    drift: 'baseline  frozen\non_tool_drift  block\ndiff  description, inputSchema',
    approval: 'idle',
    approvalTone: 'hold',
    highlight: ['drift'],
    audit: [
      '12:04:19  sess_9x2k  stripe.create_payment    BLOCK    tool_drift',
      '12:04:19  sess_9x2k  drifted_aspects          schema   description, inputSchema',
      '12:04:19  sess_9x2k  would_forward            false    until reviewed',
    ],
  },
  audit: {
    id: 'audit',
    label: '06 Audit',
    stamp: 'allowed + logged',
    stampTone: 'info',
    client: 'CrewAI',
    upstream: 'stripe',
    tool: 'stripe.create_payment',
    args: [
      ['amount ', { strong: '$18.00' }, ' USD'],
      ['forwarded. logged. nothing blocked yet.'],
    ],
    policy: 'policies:\n  default: allow\n  rules: []\n# add rules when ready',
    evidence: 'requires  —\ndepends   none\ngrounding observed',
    drift: 'baseline  capturing\non_tool_drift  log\ndiff  none',
    approval: 'off',
    approvalTone: 'ok',
    highlight: ['audit'],
    audit: [
      '12:04:22  sess_9x2k  stripe.create_payment    ALLOW    default_allow',
      '12:04:22  sess_9x2k  audit_record             stored   helio-audit.db',
      '12:04:22  sess_9x2k  upstream_response        captured 200',
    ],
  },
  repair: {
    id: 'repair',
    label: '07 Self-repair',
    stamp: 'deny + hint',
    stampTone: 'deny',
    client: 'Claude',
    upstream: 'shop',
    tool: 'process_refund',
    args: [['order ', { strong: '9182' }], ['blocked and told how to continue']],
    policy: 'feedback:\n  message: Order lookup required\n  suggestion: Call orders.lookup, then retry',
    evidence: 'requires  [orders.lookup]\ndepends   process_refund ← lookup\ngrounding missing',
    drift: 'baseline  frozen\non_tool_drift  block\ndiff  none',
    approval: 'idle',
    approvalTone: 'hold',
    highlight: ['evidence', 'audit', 'repair'],
    audit: [
      '12:04:27  sess_9x2k  process_refund           DENY     evidence_missing',
      '12:04:27  sess_9x2k  self_repair              next     call orders.lookup',
      '12:04:27  sess_9x2k  retry_when               present  orders.lookup',
    ],
  },
}
